remote_theme: just-the-docs/just-the-docs

title: Connected Interaction Kit
color_scheme: connected-interaction-kit

callouts_level: quiet
callouts:
  highlight:
    color: red
  highlight-yellow:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: red
  note-purple:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-redirect-from
